### ISSUE TITLE
Design document

### ISSUE THREAD

**Issue by mquandalle** [apollostack/apollo#27]
Maybe the high level design document could be moved into the documentation?

**Comment by stubailo** [comment]
Hey, I think having it in the docs will be distracting, since it's (a) not implemented yet (b) might change dramatically when we do get around to implementing reactivity and (c) not actively updated. I'd rather have people focus on the stuff they can use today and short-term improvements rather than get bogged down in long-term design discussions. What do you think?

**Comment by stubailo** [comment]
Closing due to no response, but in general we should make this repo better structured.
