### ISSUE TITLE
What will happen for slow queries.

### ISSUE THREAD

**Issue by krizka** [apollostack/apollo#30]
I just wonder, what if: we have some front-end components, which composes a relatively big query, then Relay merge it together and send to GraphQL endpoint, it resolves part of the query fast, and then one of resolvers trying to get some REST and get timeout on it. Will the entire query timeout? Can we avoid such a situation and send answers partially? Or it is already done?

**Comment by helfer** [comment]
In GraphQL `null` can be returned when a resolve function fails. That also applies to REST requests with timeout.

However, the whole request returns at the same time. Streaming partial responses is not currently supported, but it's something we plan to do in some way or another in the future. For the time being, if you expect part of a query to take significantly longer than other parts, or if you need some parts sooner than others, you should break up your query into several smaller ones.

**Comment by krizka** [comment]
No, Im not saying about failing, just a long async. Ok, sure I can make different requests for slow and fast parts, but isnt it right, that that graphql merges all requests made in one tick? It may easily happen right after first page loading. If it not merges requests and make it separately - it can be a workaround.

**Comment by helfer** [comment]
GraphQL-JS itself doesn't have a timeout for queries, so when it times out will depend on your browser and maybe proxy servers in between. If your GraphQL server makes any REST requests, they should have a reasonable timeout that's shorter than that. The timeout should be quite short, because the GraphQL response won't be sent until all values have either been resolved or thrown an error.

**Comment by krizka** [comment]
The question im trying to address is not about timeouts itself, It is: will queries from different components be merged if made in the same time? And if Yes, then, will we have control over this process?
Sorry for this miswriting, my english is not excellent.

**Comment by krizka** [comment]
Also, maybe we have to have some kind of profiler for resolvers and entire queries, in the simpliest form it can just log slow queries as many db's does.

**Comment by helfer** [comment]
Ah, ok, now I understand. We actually don't use Relay, but we use Apollo-client. I believe the client doesn't merge queries right now, all it does is check if the query (or parts of it) have already been cached. So the case you mentioned can't happen at the moment.

I believe this is also true of Relay, where you have to merge queries by hand.

As for the profiler, we are working on something called tracer, which should provide insight into execution of queries across the client and server.

Btw, since this issue is about apollo-client, it may be better to post it there: https://github.com/apollostack/apollo-client

**Comment by krizka** [comment]
Thanks for answers! Pretty sure the tracer will be cool!

**Comment by stubailo** [comment]
Note that Relay has some features about marking parts of your query more or less "required", so you can get the results you really care about faster. Something we should definitely look into so that people can make the initial data fetch fast!
